blank_issues_enabled: false
contact_links:
  - name: 💬 Discussions and Suggestions
    url: https://github.com/alaltitov/Guition-ESP32-S3-4848S040/discussions
    about: Use Discussions for questions, suggestions, and general discussions