substitutions:

  light_entity_1: "light.cbe_rgbcw_wi_fi_bluetooth_light"
  light_entity_2: "light.cbe_rgbcw_wi_fi_bluetooth_light"
  light_entity_3: "light.ceiling_lights"
  light_entity_4: "light.office_rgbw_lights"

  light_widget_name_1: "light1"
  light_widget_name_2: "light2"
  light_widget_name_3: "light3"
  light_widget_name_4: "light4"


  label_name_1: "spotlights 1"
  label_name_2: "ceiling lamp"
  label_name_3: "night lamp"
  label_name_4: "pendant lamp"

packages:
  light_panel: !include lights_panel.yaml

  light_1: !include
    file: light_rgb_widget.yaml
    vars:
      light_entity: "${light_entity_1}"
      widget_name: "${light_widget_name_1}"
      
  light_2: !include
    file: light_rgb_widget_slider.yaml
    vars:
      light_entity: "${light_entity_2}"
      widget_name: "${light_widget_name_2}"
      
  light_3: !include
    file: light_temp_color_widget.yaml
    vars:
      light_entity: "${light_entity_3}"
      widget_name: "${light_widget_name_3}"

  light_4: !include
    file: light_brightness_widget.yaml
    vars:
      light_entity: "${light_entity_4}"
      widget_name: "${light_widget_name_4}"


